name: samplepackagename
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  # Required dependencies
  # Optional dependencies
  # test
  - pytest>=6
  - pytest-cov>=3
  # docs
  - sphinx>=7.0
  - myst-parser>=0.13
  - sphinx-copybutton
  - sphinx-autodoc-typehints
  - furo>=2023.08.17
  - nbsphinx
  - ipykernel
  # dev
  - ipykernel
  - jupyterlab
  # below packages need to be installed with pip (aren't available in conda-forge)
  # - pip
  # - pip:
  #     -
