name: documentation

on: [push, pull_request, workflow_dispatch]

# This job installs dependencies, builds the html, and pushes it to gh-pages
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }} # only run one of these jobs at a time
    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v4

        # Install dependencies
      - name: Setup Mambaforge
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: samplepackagename

      # Build the documentation
      - name: Build the documentation
        run: uvx nox -s doc --non-interactive

      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4
        # Only publish if the main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          publish_branch: gh-pages
          # force_orphan: true
